name: Cypress Tests

on:
  pull_request:
  push:
    branches: [ main ]


jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine modified files
        id: modified_files
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
          git fetch --no-tags --depth=1 origin ${{ github.head_ref }}
          # get the actual source for two branches
          git checkout origin/${{ github.base_ref }}
          git checkout origin/${{ github.head_ref }}
          # get back to the merge commit
          git checkout ${{ github.sha }}
          git diff --name-status a76ff8177dbb8b87c67ae27c2c401288f434c293
