name: Cypress Tests

on:
  pull_request:
  push:
    branches: [ main ]


jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine modified files
        id: modified_files
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
          ADDED_MODIFIED_TESTS=$(git diff --name-status origin/$GITHUB_BASE_REF HEAD -- cypress/e2e | grep -E '^[AM]' | cut -f2)
          TESTS_PATHS=$(echo "$ADDED_MODIFIED_TESTS" | tr "\n" "," | sed 's/.$//')
          echo "test_paths=$TESTS_PATHS" >> "$GITHUB_ENV"

      - name: Print modified files
        id: asdf
        run: |
          echo $test_paths
          echo Dupa
          echo ${{ env.test_paths }}
    
      - name: Run Modified Tests
        uses: cypress-io/github-action@v5
        with:
          spec: ${{ env.test_paths }}
