name: Cypress Tests

on:
  pull_request:
  push:
    branches: [ main ]


jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can change the Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Determine modified files
        id: modified_files
        run: |
          echo Hello world from $GITHUB_BASE_REF!
          echo Hello world from $GITHUB_HEAD_REF!
          CHANGED=`git diff --name-status origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF -- cypress/e2e`
          echo $CHANGED
