name: Cypress Tests

on:
  pull_request:
  push:
    branches: [ main ]


jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: |
          CHANGED_SPECS=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }})
          echo $CHANGED_SPECS
