name: Cypress Tests

on:
  pull_request:
  push:
    branches: [ main ]


jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine modified files
        id: modified_files
        run: |
          echo `git ls-remote`
          echo Costam
          git ls-remote
          CHANGED=`git diff --name-status origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF -- cypress/e2e | grep -E '^[AM]'`
          echo $CHANGED
