name: Test reusable workflow

on:
  pull_request:  
  push:
    branches: [ main ]

jobs:
  call-workflow-passing-data:
    uses: bbrozyna/messing-with-cypress/.github/workflows/reusable.yml
    with:
      config-path: okonokonoknon
