name: Test reusable workflow

on:
  pull_request:  
  push:
    branches: [ main ]

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yml
    with:
      spec-path: "cypress/e2e/ci-test-example/**"

